packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@firebase/util'
  - '@prisma/engines'
  - '@sentry/cli'
  - bufferutil
  - core-js
  - msw
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
